In [55]:
using ForwardDiff
using Distributions
using BenchmarkTools

In [56]:
include("Rosenbrock_Stochastic.jl")
include("Exponential_Stochastic.jl")
include("Rosenbrock_Generalized_Stochastic.jl")
include("Rosenbrock_Generalized_Stochastic_2.jl")

Hessian_vector_product_RGS (generic function with 1 method)

# Essai fonction Rosenbrock

## Generation sample

In [36]:
σ = 0.1
ξ = rand(Normal(1, σ), 1000)

1000-element Array{Float64,1}:
 0.9451917336940948
 0.7800451866701468
 0.951603847767299
 1.0897004473916756
 0.973493845215048
 1.04703661472569
 0.9766569758305788
 1.012494293497825
 1.0145373484912417
 0.8988816674071098
 1.082255714244672
 1.2098480702569643
 1.093293540033049
 ⋮
 0.9939671196550237
 1.0772603625384434
 0.984816065565509
 1.0576857677415876
 0.9239100755515063
 1.1278666517431593
 1.0185526385388561
 1.006307840573932
 1.045322726839023
 0.8696860075588897
 1.1062897523313935
 0.979344141664611

In [4]:
x = [1;1]
Rosenbrock_Sto(x, ξ)

4.239127057557019

### Verification Gradient 

In [5]:
Rosenbrock_Sto_Grad(x, ξ)

2-element Array{Float64,1}:
 15.511929418841808
  0.7045330137070027

In [6]:
function f(x::Vector)
return Rosenbrock_Sto(x, ξ) 
end

f (generic function with 1 method)

In [7]:
ForwardDiff.gradient(f, x)

2-element Array{Float64,1}:
 15.511929418841811
  0.7045330137070027

### Verification Hessian

In [8]:
ForwardDiff.hessian(f, x)

2×2 Array{Float64,2}:
  845.689  -398.591
 -398.591   200.0

# Fonction exponential

$$f(x) = \mathbb{E}\Big[ -\mathrm{e}^{-0.5 \Vert \xi x \Vert^2} \Big] $$

where,
- $x = (x_1, \dots, x_p)^T$ ,
- $\xi \in \mathbb{R}$ is a random variable.

  ## Generation sample


In [9]:
σ = 0.1
ξ = rand(Normal(1, σ), 1000)

p = 50
x = ones(p)

50-element Array{Float64,1}:
 1.0
 1.0
 1.0
 1.0
 1.0
 1.0
 1.0
 1.0
 1.0
 1.0
 1.0
 1.0
 1.0
 ⋮
 1.0
 1.0
 1.0
 1.0
 1.0
 1.0
 1.0
 1.0
 1.0
 1.0
 1.0
 1.0

In [10]:
@time Exponential_Sto(x, ξ)

  0.186924 seconds (236.18 k allocations: 12.814 MiB, 11.48% gc time)


-1.7863346732814494e-7

In [11]:
function f_exp(x::Vector)
return Exponential_Sto(x, ξ) 
end

f_exp (generic function with 1 method)

### Verification gradient

In [12]:
@time grad_FD = ForwardDiff.gradient(f_exp, x)

  1.230790 seconds (2.26 M allocations: 137.224 MiB, 3.43% gc time)


50-element Array{Float64,1}:
 6.82858757500516e-8
 6.82858757500516e-8
 6.82858757500516e-8
 6.82858757500516e-8
 6.82858757500516e-8
 6.82858757500516e-8
 6.82858757500516e-8
 6.82858757500516e-8
 6.82858757500516e-8
 6.82858757500516e-8
 6.82858757500516e-8
 6.82858757500516e-8
 6.82858757500516e-8
 ⋮
 6.82858757500516e-8
 6.82858757500516e-8
 6.82858757500516e-8
 6.82858757500516e-8
 6.82858757500516e-8
 6.82858757500516e-8
 6.82858757500516e-8
 6.82858757500516e-8
 6.82858757500516e-8
 6.82858757500516e-8
 6.82858757500516e-8
 6.82858757500516e-8

In [13]:
@time grad =  Exponential_Sto_Grad(x, ξ)

  0.124917 seconds (185.55 k allocations: 9.952 MiB)


50-element Array{Float64,1}:
 6.828587575005136e-8
 6.828587575005136e-8
 6.828587575005136e-8
 6.828587575005136e-8
 6.828587575005136e-8
 6.828587575005136e-8
 6.828587575005136e-8
 6.828587575005136e-8
 6.828587575005136e-8
 6.828587575005136e-8
 6.828587575005136e-8
 6.828587575005136e-8
 6.828587575005136e-8
 ⋮
 6.828587575005136e-8
 6.828587575005136e-8
 6.828587575005136e-8
 6.828587575005136e-8
 6.828587575005136e-8
 6.828587575005136e-8
 6.828587575005136e-8
 6.828587575005136e-8
 6.828587575005136e-8
 6.828587575005136e-8
 6.828587575005136e-8
 6.828587575005136e-8

In [14]:
norm(grad_FD - grad)

1.6845264587585898e-21

### Verification Hessian

In [15]:
@time hessian_FD = ForwardDiff.hessian(f_exp, x)

  5.709801 seconds (4.57 M allocations: 1.330 GiB, 4.41% gc time)


50×50 Array{Float64,2}:
  4.14035e-8  -2.68824e-8  -2.68824e-8  …  -2.68824e-8  -2.68824e-8
 -2.68824e-8   4.14035e-8  -2.68824e-8     -2.68824e-8  -2.68824e-8
 -2.68824e-8  -2.68824e-8   4.14035e-8     -2.68824e-8  -2.68824e-8
 -2.68824e-8  -2.68824e-8  -2.68824e-8     -2.68824e-8  -2.68824e-8
 -2.68824e-8  -2.68824e-8  -2.68824e-8     -2.68824e-8  -2.68824e-8
 -2.68824e-8  -2.68824e-8  -2.68824e-8  …  -2.68824e-8  -2.68824e-8
 -2.68824e-8  -2.68824e-8  -2.68824e-8     -2.68824e-8  -2.68824e-8
 -2.68824e-8  -2.68824e-8  -2.68824e-8     -2.68824e-8  -2.68824e-8
 -2.68824e-8  -2.68824e-8  -2.68824e-8     -2.68824e-8  -2.68824e-8
 -2.68824e-8  -2.68824e-8  -2.68824e-8     -2.68824e-8  -2.68824e-8
 -2.68824e-8  -2.68824e-8  -2.68824e-8  …  -2.68824e-8  -2.68824e-8
 -2.68824e-8  -2.68824e-8  -2.68824e-8     -2.68824e-8  -2.68824e-8
 -2.68824e-8  -2.68824e-8  -2.68824e-8     -2.68824e-8  -2.68824e-8
  ⋮                                     ⋱               
 -2.68824e-8  -2.68824e-8  -2.68824

In [16]:
@time hessian = Exponential_Sto_Hessian(x, ξ)

  0.224439 seconds (300.58 k allocations: 15.599 MiB, 4.51% gc time)


50×50 Array{Float64,2}:
  4.14035e-8  -2.68824e-8  -2.68824e-8  …  -2.68824e-8  -2.68824e-8
 -2.68824e-8   4.14035e-8  -2.68824e-8     -2.68824e-8  -2.68824e-8
 -2.68824e-8  -2.68824e-8   4.14035e-8     -2.68824e-8  -2.68824e-8
 -2.68824e-8  -2.68824e-8  -2.68824e-8     -2.68824e-8  -2.68824e-8
 -2.68824e-8  -2.68824e-8  -2.68824e-8     -2.68824e-8  -2.68824e-8
 -2.68824e-8  -2.68824e-8  -2.68824e-8  …  -2.68824e-8  -2.68824e-8
 -2.68824e-8  -2.68824e-8  -2.68824e-8     -2.68824e-8  -2.68824e-8
 -2.68824e-8  -2.68824e-8  -2.68824e-8     -2.68824e-8  -2.68824e-8
 -2.68824e-8  -2.68824e-8  -2.68824e-8     -2.68824e-8  -2.68824e-8
 -2.68824e-8  -2.68824e-8  -2.68824e-8     -2.68824e-8  -2.68824e-8
 -2.68824e-8  -2.68824e-8  -2.68824e-8  …  -2.68824e-8  -2.68824e-8
 -2.68824e-8  -2.68824e-8  -2.68824e-8     -2.68824e-8  -2.68824e-8
 -2.68824e-8  -2.68824e-8  -2.68824e-8     -2.68824e-8  -2.68824e-8
  ⋮                                     ⋱               
 -2.68824e-8  -2.68824e-8  -2.68824

In [17]:
norm(hessian_FD - hessian)

4.233419542593993e-21

### Verification produit Hessian-vector

In [40]:
v = randn(p)
hessian = Exponential_Sto_Hessian(x, ξ)

@time Hes_Vect = Hessian_vector_product_SExp(x, ξ, v)

  0.015107 seconds (1.00 k allocations: 485.344 KiB)


50-element Array{Float64,1}:
  1.591481009842857e-8
  9.618859906348064e-9
  2.8635363776504793e-8
 -2.2502018358320405e-8
 -1.2535462688255825e-8
  1.4771752178184963e-8
  3.263127136648112e-8
 -2.0906325812251035e-9
 -1.9223628093542902e-8
 -2.0258817405286473e-9
  6.5331882055142284e-9
 -2.5294225208401723e-8
  2.021142728636366e-8
  ⋮
 -3.1804194600680284e-8
  8.216932284766826e-10
  6.10662109833299e-8
  1.5333104808294616e-8
 -4.3158634443265525e-9
 -9.899010320653623e-9
  3.510846797231401e-9
  3.503535199165246e-8
  5.183940918950234e-8
  5.775363769558742e-8
  2.2625937298559023e-8
 -3.5081030448452526e-8

In [41]:
norm(Hes_Vect - hessian*v)

9.036234614217158e-22

# Rosenbrock Generalized (same minima)

$$ f(x) = \mathbb{E}\left[\sum_{i =1}^{p-1} 100\xi_i \Big( x_{i+1} - x_i^2 \Big)^2  +  \Big( x_i - 1 \Big)^2 \right]$$

with, 
- $x \in \mathbb{R}^p$
- $\xi \in \mathbb{R}^{p-1}$ a random vector.

In [18]:
p = 50
x = randn(p)
N = 10000

10000

In [19]:
ξ = rand(p-1, N)

49×10000 Array{Float64,2}:
 0.390702    0.640613   0.12818   …  0.950841    0.661753   0.976021
 0.579486    0.733896   0.558789     0.213586    0.751715   0.536771
 0.231397    0.977881   0.858903     0.506298    0.811279   0.50145
 0.799396    0.508909   0.634051     0.799504    0.0159536  0.834034
 0.6376      0.745673   0.322793     0.65397     0.471017   0.150458
 0.899688    0.999513   0.194278  …  0.788872    0.856511   0.980022
 0.00549111  0.296006   0.260961     0.598856    0.550664   0.884085
 0.37889     0.243331   0.811711     0.771494    0.830431   0.766405
 0.0707942   0.630192   0.440426     0.791262    0.519011   0.615359
 0.533913    0.233024   0.569886     0.00816466  0.463595   0.402059
 0.473815    0.887633   0.198791  …  0.124015    0.572122   0.619049
 0.509505    0.847352   0.490592     0.481762    0.506747   0.121305
 0.79944     0.71782    0.988161     0.551752    0.81099    0.223892
 ⋮                                ⋱                         
 0.149269    0.5

In [20]:
Rosenbrock_Generalized_Stochastic(x, ξ)

9157.546746320302

In [21]:
function f_gen_ros(x::Vector)
   return  Rosenbrock_Generalized_Stochastic(x, ξ)
end

f_gen_ros (generic function with 1 method)

### Verification gradient

In [22]:
@time grad = Rosenbrock_Generalized_Stochastic_Grad(x, ξ)

  0.066425 seconds (60.36 k allocations: 7.305 MiB)


50-element Array{Float64,1}:
  -125.92277673515929
   -90.66666759401281
   -13.533771938647874
    16.15735805299341
   -10.617495460654766
   208.4497033037291
  -131.67638337547208
   639.715758617031
  -257.5272907356459
    90.82153338187861
  -135.96975255818282
   714.3437522758966
  -199.92006634114477
     ⋮
   991.903683641435
   -90.23529178088276
 -3486.720254659161
  -710.9181239678772
   -24.395880943722506
   233.3385336853398
  -125.02403701808424
  -419.72598786361505
  -296.9060493576827
 -2242.868885547798
  -490.45292521631205
     8.663561244240421

In [23]:
@time grad_FD = ForwardDiff.gradient(f_gen_ros, x)

  0.813135 seconds (1.50 M allocations: 96.857 MiB, 2.95% gc time)


50-element Array{Float64,1}:
  -125.92277673515929
   -90.66666759401211
   -13.53377193864788
    16.157358052993494
   -10.617495460654824
   208.44970330373096
  -131.6763833754721
   639.7157586170307
  -257.5272907356461
    90.82153338187864
  -135.96975255818367
   714.3437522758971
  -199.92006634114475
     ⋮
   991.9036836414306
   -90.23529178088216
 -3486.720254659122
  -710.9181239678761
   -24.395880943722396
   233.33853368534
  -125.02403701808457
  -419.72598786361635
  -296.9060493576833
 -2242.868885547801
  -490.4529252163128
     8.663561244240421

In [24]:
norm(grad - grad_FD)

4.154486148233661e-11

### Verification Hessian

In [25]:
function f_gen_ros(x::Vector)
   return  Rosenbrock_Generalized_Stochastic(x, ξ)
end

f_gen_ros (generic function with 1 method)

In [26]:
@time hessian = Rosenbrock_Generalized_Stochastic_Hessian(x, ξ)

  0.121566 seconds (82.63 k allocations: 8.448 MiB)


50×50 Array{Float64,2}:
 401.873  156.078    0.0       0.0     …     0.0       0.0      0.0
 156.078  167.467   36.5861    0.0           0.0       0.0      0.0
   0.0     36.5861  56.6233   44.6895        0.0       0.0      0.0
   0.0      0.0     44.6895  118.733         0.0       0.0      0.0
   0.0      0.0      0.0     -76.0286        0.0       0.0      0.0
   0.0      0.0      0.0       0.0     …     0.0       0.0      0.0
   0.0      0.0      0.0       0.0           0.0       0.0      0.0
   0.0      0.0      0.0       0.0           0.0       0.0      0.0
   0.0      0.0      0.0       0.0           0.0       0.0      0.0
   0.0      0.0      0.0       0.0           0.0       0.0      0.0
   0.0      0.0      0.0       0.0     …     0.0       0.0      0.0
   0.0      0.0      0.0       0.0           0.0       0.0      0.0
   0.0      0.0      0.0       0.0           0.0       0.0      0.0
   ⋮                                   ⋱                      
   0.0      0.0      0.0     

In [27]:
@time hessian_FD = ForwardDiff.hessian(f_gen_ros, x)

  7.307379 seconds (4.17 M allocations: 295.275 MiB, 1.19% gc time)


50×50 Array{Float64,2}:
 401.873  156.078    0.0       0.0     …     0.0       0.0      0.0
 156.078  167.467   36.5861    0.0           0.0       0.0      0.0
   0.0     36.5861  56.6233   44.6895        0.0       0.0      0.0
   0.0      0.0     44.6895  118.733         0.0       0.0      0.0
   0.0      0.0      0.0     -76.0286        0.0       0.0      0.0
   0.0      0.0      0.0       0.0     …     0.0       0.0      0.0
   0.0      0.0      0.0       0.0           0.0       0.0      0.0
   0.0      0.0      0.0       0.0           0.0       0.0      0.0
   0.0      0.0      0.0       0.0           0.0       0.0      0.0
   0.0      0.0      0.0       0.0           0.0       0.0      0.0
   0.0      0.0      0.0       0.0     …     0.0       0.0      0.0
   0.0      0.0      0.0       0.0           0.0       0.0      0.0
   0.0      0.0      0.0       0.0           0.0       0.0      0.0
   ⋮                                   ⋱                      
   0.0      0.0      0.0     

In [28]:
norm(hessian - hessian_FD)

3.802456504884408e-11

### Verification product Hessian-vector

In [29]:
v = randn(p)

50-element Array{Float64,1}:
  0.4949676564671313
 -0.7877757291609309
  0.5561530359836312
 -0.5930846751327921
 -0.4919101762358255
  1.0452145332169664
 -0.1385534700791777
  0.42428934816988
 -1.0634424949066257
 -0.4261465364309495
  1.0392350937223858
 -1.557319857937176
 -0.006577332668137154
  ⋮
 -0.42648466051394734
 -0.41785004093911166
 -0.9521383846370245
 -0.2164430670530749
 -0.21754843215566116
  0.15613505698096472
 -1.123989758803633
  0.5565512175929754
 -0.47073200891186867
 -1.9920212655098772
  0.36417756409894086
  1.6853054379771926

In [30]:
hessian = Rosenbrock_Generalized_Stochastic_Hessian(x, ξ)

@time Hes_vect = Hessian_vector_product_RGS(x, ξ, v)

  0.094952 seconds (66.79 k allocations: 7.584 MiB)


50-element Array{Float64,1}:
    75.95963226950471
   -34.32512144960983
   -23.835100134760253
    -8.165325460993133
   -58.357449031368525
   598.3735385713609
  -104.91227332262176
   929.0495746051315
  -154.73759022799248
  -247.3281933419561
   190.48692152463667
 -2189.879651543853
   440.8368819377954
     ⋮
  -583.1117213872028
   -69.9945000956273
 -3725.4496507910394
  -560.8346845983184
    -7.3901704789422045
   275.0798767133592
  -378.2260363053049
   332.01182890928163
  -292.5793133935165
 -5302.2234537929135
  -271.15622523869484
   242.3979658126069

In [32]:
norm(Hes_vect - hessian*v)

2.668993607320649e-11

# Verification Generalised Rosenbrock  (different minima)

$$f(x) =  \mathbb{E}\left[  \sum_{i =1}^{p-1} 100\Big( x_{i+1} - \big(\xi_i x_i\big)^2 \Big)^2  + \Big( \xi_i x_i - 1 \Big)^2 \right]$$

with, 
- $x \in \mathbb{R}^p$
- $\xi \in \mathbb{R}^{p-1}$ a random vector.

## Generation sample

In [22]:
p = 50
x = randn(p)
N = 10000

10000

In [23]:
ξ = rand(p-1, N)

49×10000 Array{Float64,2}:
 0.739227    0.621232   0.853916   …  0.645406   0.914331   0.084892
 0.235819    0.857906   0.800603      0.95898    0.608172   0.618866
 0.579761    0.907282   0.5584        0.176482   0.43042    0.0893103
 0.0143135   0.968866   0.0303707     0.808795   0.792164   0.118813
 0.193174    0.106693   0.016969      0.0477174  0.36205    0.95558
 0.194       0.278367   0.458418   …  0.391004   0.251492   0.520711
 0.847883    0.487641   0.898001      0.647469   0.210027   0.981168
 0.533169    0.353522   0.109394      0.436386   0.201434   0.899587
 0.0348284   0.434134   0.927493      0.019425   0.304287   0.862767
 0.898244    0.874126   0.173437      0.996968   0.591216   0.14131
 0.367633    0.0895651  0.0240052  …  0.229476   0.165406   0.185102
 0.637217    0.0541967  0.178691      0.347817   0.606401   0.922495
 0.0167314   0.862689   0.224328      0.972492   0.128128   0.100928
 ⋮                                 ⋱                        
 0.519342    0.3

### Verification function

In [24]:
Rosenbrock_Generalized_Stochastic_2(x, ξ)

7391.405215881385

In [25]:
function f_RGS_diff(x::Vector)
   return Rosenbrock_Generalized_Stochastic_2(x, ξ) 
end

f_RGS_diff (generic function with 1 method)

### Verification gradient

In [38]:
@time direct_grad = Rosenbrock_Generalized_Stochastic_Grad_2(x, ξ)

  0.188601 seconds (63.03 k allocations: 7.416 MiB)


50-element Array{Float64,1}:
   -4.877696556300543
  -88.25924058777053
  -11.22563827304007
  566.5588105116764
 -158.74532381637636
   39.56157103631435
 1725.7678574681186
 -331.7572011365253
 1661.728787036221
 -605.6012689728025
  -58.19020309640134
  188.64128470612292
  -29.556256638573245
    ⋮
 -146.07850382677606
  -80.724629564326
   74.33662688553943
   95.89320575689408
  207.05517682511845
 -266.7820417078642
  -73.38055479051046
  166.06591421127555
  111.59817501035286
  -50.074005396423765
   -8.93204790592544
  262.32280083506276

In [39]:
@time forward_grad = ForwardDiff.gradient(f_RGS_diff, x)

  0.446969 seconds (107.76 k allocations: 26.289 MiB, 7.71% gc time)


50-element Array{Float64,1}:
   -4.877696556300543
  -88.25924058777022
  -11.225638273040055
  566.558810511674
 -158.7453238163759
   39.561571036314525
 1725.7678574681188
 -331.7572011365273
 1661.728787036211
 -605.6012689728011
  -58.190203096401284
  188.64128470612218
  -29.556256638573437
    ⋮
 -146.07850382677663
  -80.72462956432543
   74.33662688553925
   95.89320575689428
  207.05517682511882
 -266.7820417078628
  -73.38055479051026
  166.0659142112745
  111.59817501035366
  -50.07400539642387
   -8.932047905925357
  262.32280083506276

In [40]:
norm(direct_grad - forward_grad)

1.3555460463878416e-11

In [41]:
direct_grad - forward_grad

50-element Array{Float64,1}:
  0.0
 -3.126388037344441e-13
 -1.5987211554602254e-14
  2.3874235921539366e-12
 -4.547473508864641e-13
 -1.7763568394002505e-13
 -2.2737367544323206e-13
  2.0463630789890885e-12
  1.000444171950221e-11
 -1.3642420526593924e-12
 -5.684341886080802e-14
  7.389644451905042e-13
  1.9184653865522705e-13
  ⋮
  5.684341886080801e-13
 -5.684341886080801e-13
  1.8474111129762605e-13
 -1.9895196601282805e-13
 -3.694822225952521e-13
 -1.4210854715202004e-12
 -1.9895196601282805e-13
  1.0516032489249483e-12
 -7.958078640513122e-13
  1.0658141036401503e-13
 -8.348877145181177e-14
  0.0

### Verification Hessian

In [57]:
@time hessian_direct = Rosenbrock_Generalized_Stochastic_Hessian_2(x, ξ)

  0.303943 seconds (86.82 k allocations: 8.615 MiB)


50×50 Array{Float64,2}:
 49.7651   10.6504   0.0        0.0     …    0.0       0.0        0.0
 10.6504  265.012   47.8706     0.0          0.0       0.0        0.0
  0.0      47.8706  16.8997    33.3264       0.0       0.0        0.0
  0.0       0.0     33.3264   739.388        0.0       0.0        0.0
  0.0       0.0      0.0     -200.059        0.0       0.0        0.0
  0.0       0.0      0.0        0.0     …    0.0       0.0        0.0
  0.0       0.0      0.0        0.0          0.0       0.0        0.0
  0.0       0.0      0.0        0.0          0.0       0.0        0.0
  0.0       0.0      0.0        0.0          0.0       0.0        0.0
  0.0       0.0      0.0        0.0          0.0       0.0        0.0
  0.0       0.0      0.0        0.0     …    0.0       0.0        0.0
  0.0       0.0      0.0        0.0          0.0       0.0        0.0
  0.0       0.0      0.0        0.0          0.0       0.0        0.0
  ⋮                                     ⋱                       
 

In [58]:
@time hessian_diff = ForwardDiff.hessian(f_RGS_diff, x)

  7.906569 seconds (734.11 k allocations: 135.541 MiB, 0.74% gc time)


50×50 Array{Float64,2}:
 49.7651   10.6504   0.0        0.0     …    0.0       0.0        0.0
 10.6504  265.012   47.8706     0.0          0.0       0.0        0.0
  0.0      47.8706  16.8997    33.3264       0.0       0.0        0.0
  0.0       0.0     33.3264   739.388        0.0       0.0        0.0
  0.0       0.0      0.0     -200.059        0.0       0.0        0.0
  0.0       0.0      0.0        0.0     …    0.0       0.0        0.0
  0.0       0.0      0.0        0.0          0.0       0.0        0.0
  0.0       0.0      0.0        0.0          0.0       0.0        0.0
  0.0       0.0      0.0        0.0          0.0       0.0        0.0
  0.0       0.0      0.0        0.0          0.0       0.0        0.0
  0.0       0.0      0.0        0.0     …    0.0       0.0        0.0
  0.0       0.0      0.0        0.0          0.0       0.0        0.0
  0.0       0.0      0.0        0.0          0.0       0.0        0.0
  ⋮                                     ⋱                       
 

In [59]:
norm(hessian_direct - hessian_diff)

1.0318334360610195e-11

In [60]:
hessian_direct - hessian_diff

50×50 Array{Float64,2}:
 -1.42109e-14  -6.57252e-14  0.0          …   0.0          0.0
 -6.57252e-14   0.0          2.84217e-14      0.0          0.0
  0.0           2.84217e-14  3.55271e-15      0.0          0.0
  0.0           0.0          3.90799e-13      0.0          0.0
  0.0           0.0          0.0              0.0          0.0
  0.0           0.0          0.0          …   0.0          0.0
  0.0           0.0          0.0              0.0          0.0
  0.0           0.0          0.0              0.0          0.0
  0.0           0.0          0.0              0.0          0.0
  0.0           0.0          0.0              0.0          0.0
  0.0           0.0          0.0          …   0.0          0.0
  0.0           0.0          0.0              0.0          0.0
  0.0           0.0          0.0              0.0          0.0
  ⋮                                       ⋱                
  0.0           0.0          0.0              0.0          0.0
  0.0           0.0          0.0  

### Verification produit Hessian-vector

In [61]:
v = rand(p)

@time prod_direct = Hessian_vector_product_RGS_2(x, ξ, v)

  0.242317 seconds (72.42 k allocations: 7.829 MiB)


50-element Array{Float64,1}:
   56.83700785375165
  293.0967558054424
   78.60247389413736
  426.29219805836834
  -40.29269200621028
  -31.23144089643326
  302.36882917791866
   82.9038409521526
 1194.210774235734
  207.83370740463943
  146.49375218817585
  242.3179659304301
  -87.17028904046796
    ⋮
   95.66421381884398
   72.31177486534223
   13.598533723680012
   33.39000012757475
  189.46479902080856
  258.3689839988861
  208.0682670592833
  192.24722085471421
  118.38338874764186
  145.37001478320212
   48.410903873957686
  151.71577016444962

In [62]:
norm(prod_direct - hessian_diff*v)

9.722996703527017e-12